version: "2"
run:
  go: "1.24"
  tests: false
  allow-parallel-runners: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - cyclop
    - dupl
    - errchkjson
    - errname
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gosec
    - importas
    - lll
    - misspell
    - nilerr
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - sqlclosecheck
    - testpackage
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - .*\.gen\.go$
      # don't go out there bro, u don't wanna lint it.
      - ^internal/db/db.*\.go$
      - ^internal/db/filter.*\.go$
      - ^internal/db/model\.go$
      - ^internal/db/model_search\.go$
      - ^internal/db/model_validate\.go$
      - ^internal/db/options\.go$
      - ^internal/db/news\.go$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
