services:

  dev_database:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:${DB_HOST_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 5s
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ../db/schema/withoutmedianews.sql:/docker-entrypoint-initdb.d/001-schema.sql
      - ../db/testdata/testdata.sql:/docker-entrypoint-initdb.d/100-testdata.sql