-- =============================================================================
-- Diagram Name: newswithoutmedia
-- Created on: 9/15/2025 2:34:38 PM
-- Diagram Version: 
-- =============================================================================


CREATE TABLE "categories" (
	"categoryId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"sort" int4 DEFAULT NULL,
	"statusId" int4 NOT NULL DEFAULT 2,
	PRIMARY KEY("categoryId")
);

CREATE TABLE "statuses" (
	"statusId" int4 NOT NULL,
	PRIMARY KEY("statusId")
);

CREATE TABLE "tags" (
	"tagId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(64) NOT NULL,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("tagId")
);

CREATE TABLE "news" (
	"newsId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"shortText" varchar(1024) NOT NULL,
	"content" text,
	"author" varchar(255),
	"categoryId" int4 NOT NULL,
	"tagIds" int4[] NOT NULL,
	"publishedAt" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL DEFAULT now(),
	"statusId" int4 NOT NULL,
	PRIMARY KEY("newsId")
);


ALTER TABLE "categories" ADD CONSTRAINT "Ref_categories_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "tags" ADD CONSTRAINT "Ref_tags_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_categories" FOREIGN KEY ("categoryId")
	REFERENCES "categories"("categoryId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_news_to_statuses" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE RESTRICT
	ON UPDATE RESTRICT
	NOT DEFERRABLE;


